# .github/workflows/R-CMD-check.yaml
# Simplified for basilisk-based Ibex (no global Keras install required)
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      # Optional: cache basilisk's miniconda to speed up repeated runs
      - uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/basilisk
          key: ${{ runner.os }}-basilisk-${{ hashFiles('DESCRIPTION') }}

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            bioc::basilisk
            bioc::basilisk.utils
          needs: cran, bioc

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
